-- 1. Create the PROFILES table
-- This links to the Supabase Auth system so every user has a profile
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  full_name TEXT,
  student_id TEXT UNIQUE,
  email TEXT,
  role TEXT CHECK (role IN ('student', 'admin')) DEFAULT 'student',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create custom "Enums" (Fixed options for status)
-- This prevents typos like "avaiable" vs "available"
CREATE TYPE item_status AS ENUM ('available', 'pending', 'returned');
CREATE TYPE claim_status AS ENUM ('pending', 'approved', 'rejected');

-- 3. Create the ITEMS table
CREATE TABLE public.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  location_found TEXT,
  image_url TEXT, -- This will store the link to the photo in Supabase Storage
  status item_status DEFAULT 'available',
  finder_id UUID REFERENCES public.profiles(id) NOT NULL
);

-- 4. Create the CLAIMS table
CREATE TABLE public.claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  item_id BIGINT REFERENCES public.items(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  proof_text TEXT NOT NULL, -- "Describe the sticker on the back," etc.
  status claim_status DEFAULT 'pending'
);
-- Trigger to create a profile automatically on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
